[project]
name = "kb26pkuser22"
version = "0.1.1"
description = ""
authors = [
    {name = "jonminix",email = "longgirl759@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "kb25pkuser34 (>=0.1.1,<0.2.0)"
]

[dependency-groups]
dev = [
    "yes (>=0.0.1,<0.0.2)",
    "pytest (>=9.1.1,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
